#include<bits/stdc++.h>
using namespace std;
int solve(int n,int k){
    if(n==1 && k==1){
        return 0;
    }
    int mid=pow(2,n-2);
    if(k<=mid){
        return solve(n-1,k);
    }
    else {
        return !solve(n-1,k-mid);
    }
}
int main(){
    cout << "This program is for calculating the kth value in a grammar generated by 1s and zeroes " << endl;
    cout << "This program is taken from leetcode" << endl;
    int n,k;
    cout << "Enter n and k" << endl;
    cin >> n >> k;
    cout << solve(n,k);

}